{{- if .Values.selebrow.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "selebrow.fullname" . }}-proxy
  labels:
    {{- include "selebrow.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.selebrow.proxy.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "selebrow.selectorLabels" . | nindent 4 }}
{{- end }}
